# Generated by Django 5.0.6 on 2026-06-13 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actividades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrenador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('especialidad', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AsistenciaEntrenador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(choices=[('PRESENTE', 'Presente'), ('AUSENTE', 'Ausente')], max_length=10)),
                ('justificada', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True)),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividades.horarioclase')),
                ('entrenador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='entrenadores.entrenador')),
            ],
            options={
                'verbose_name_plural': 'Asistencias de entrenadores',
                'unique_together': {('entrenador', 'horario', 'fecha')},
            },
        ),
    ]
