# Generated by Django 5.0.6 on 2026-06-19 00:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrenadores', '0002_entrenador_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrenador',
            name='certificado',
            field=models.FileField(help_text='PDF de certificación que acredita al entrenador', null=True, upload_to='certificados/entrenadores/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
