# Generated by Django 5.0.6 on 2026-06-20 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrenadores', '0003_entrenador_certificado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AsistenciaEntrenador',
        ),
    ]
