# Generated by Django 5.0.6 on 2026-06-13 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actividades', '0001_initial'),
        ('entrenadores', '0001_initial'),
        ('miembros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='horarioclase',
            name='entrenador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clases', to='entrenadores.entrenador'),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='horario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='actividades.horarioclase'),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='miembro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='miembros.miembro'),
        ),
        migrations.AlterUniqueTogether(
            name='inscripcion',
            unique_together={('miembro', 'horario')},
        ),
    ]
