# Generated by Django 5.0.6 on 2026-06-15 18:13

from django.db import migrations
from datetime import time


def create_test_activities(apps, schema_editor):
    """Crear actividades y horarios de prueba"""
    Actividad = apps.get_model('actividades', 'Actividad')
    HorarioClase = apps.get_model('actividades', 'HorarioClase')
    Entrenador = apps.get_model('entrenadores', 'Entrenador')

    # Crear actividades
    actividades_data = [
        ('Spinning', 'Clases de ciclismo indoor de alta intensidad', 20),
        ('Yoga', 'Clases de yoga para relajación y flexibilidad', 15),
        ('Pilates', 'Ejercicios de pilates para core y postura', 12),
        ('Pesas', 'Entrenamiento con pesas y resistencia', 25),
    ]

    actividades = {}
    for nombre, desc, capacidad in actividades_data:
        act, created = Actividad.objects.get_or_create(
            nombre=nombre,
            defaults={'descripcion': desc, 'capacidad_maxima': capacidad}
        )
        actividades[nombre] = act

    # Obtener entrenador de prueba
    entrenador = Entrenador.objects.filter(email='entrenador@test.com').first()

    if entrenador:
        # Crear horarios
        horarios_data = [
            ('Spinning', 'LUN', '07:00', '08:00'),
            ('Spinning', 'MIE', '18:30', '19:30'),
            ('Yoga', 'MAR', '09:00', '10:30'),
            ('Yoga', 'JUE', '18:00', '19:30'),
            ('Pilates', 'LUN', '10:00', '11:00'),
            ('Pilates', 'VIE', '15:00', '16:00'),
            ('Pesas', 'MAR', '06:00', '07:00'),
            ('Pesas', 'SAB', '10:00', '11:30'),
        ]

        for actividad_name, dia, h_inicio, h_fin in horarios_data:
            actividad = actividades[actividad_name]
            HorarioClase.objects.get_or_create(
                actividad=actividad,
                dia_semana=dia,
                hora_inicio=h_inicio,
                hora_fin=h_fin,
                defaults={
                    'entrenador': entrenador,
                    'sala': f'Sala {actividad_name}',
                }
            )


def delete_test_activities(apps, schema_editor):
    """Eliminar actividades de prueba"""
    Actividad = apps.get_model('actividades', 'Actividad')
    Actividad.objects.filter(nombre__in=['Spinning', 'Yoga', 'Pilates', 'Pesas']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0002_initial'),
        ('entrenadores', '0002_entrenador_usuario'),
    ]

    operations = [
        migrations.RunPython(create_test_activities, delete_test_activities),
    ]
