# Generated by Django 5.0.6 on 2026-06-13 21:06

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Miembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('foto', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='foto')),
                ('tipo_miembro', models.CharField(choices=[('REGULAR', 'Regular'), ('ESTUDIANTE', 'Estudiante'), ('MAYOR', 'Persona Mayor')], default='REGULAR', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_alta', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Carnet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_carnet', models.CharField(max_length=10, unique=True)),
                ('codigo_barras_imagen', cloudinary.models.CloudinaryField(max_length=255, verbose_name='barcode')),
                ('fecha_emision', models.DateField(auto_now_add=True)),
                ('miembro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carnet', to='miembros.miembro')),
            ],
        ),
    ]
