# Generated by Django 5.0.6 on 2026-06-13 21:12

from django.db import migrations


def create_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.get_or_create(name='Admin')
    Group.objects.get_or_create(name='Recepcion')
    Group.objects.get_or_create(name='Entrenador')


def delete_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(name__in=['Admin', 'Recepcion', 'Entrenador']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('miembros', '0001_initial'),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.RunPython(create_groups, delete_groups),
    ]
