# Generated by Django 5.0.6 on 2026-06-19 00:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros', '0003_miembro_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carnet',
            name='codigo_barras_imagen',
            field=models.ImageField(help_text='Código de barras generado automáticamente', upload_to='carnets/'),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='foto',
            field=models.ImageField(blank=True, help_text='Máximo 5MB. Formatos: JPG, PNG, GIF', null=True, upload_to='miembros/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'])]),
        ),
    ]
