# Generated by Django 5.0.6 on 2026-06-15 17:57

from django.db import migrations
from django.contrib.auth.models import User, Group


def create_test_users(apps, schema_editor):
    """Crear usuarios de prueba y grupos"""
    # Crear grupos
    groups_names = ['Admin', 'Recepcion', 'Entrenador', 'Miembro']
    groups = {}
    for name in groups_names:
        group, created = Group.objects.get_or_create(name=name)
        groups[name] = group

    # Crear usuarios
    users_data = [
        ('admin', 'admin123', 'Admin'),
        ('recepcion', '123456', 'Recepcion'),
        ('entrenador', '123456', 'Entrenador'),
        ('juan_miembro', '123456', 'Miembro'),
    ]

    for username, password, group_name in users_data:
        user, created = User.objects.get_or_create(
            username=username,
            defaults={'email': f'{username}@test.com'}
        )
        if created:
            user.set_password(password)
            user.save()
        user.groups.add(groups[group_name])


def delete_test_users(apps, schema_editor):
    """Eliminar usuarios de prueba"""
    User.objects.filter(username__in=['admin', 'recepcion', 'entrenador', 'juan_miembro']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('miembros', '0003_miembro_usuario'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RunPython(create_test_users, delete_test_users),
    ]
