# Generated by Django 5.0.6 on 2026-06-15 18:13

from django.db import migrations


def link_test_users(apps, schema_editor):
    """Vincular usuarios de prueba con sus registros"""
    User = apps.get_model('auth', 'User')
    Miembro = apps.get_model('miembros', 'Miembro')
    Entrenador = apps.get_model('entrenadores', 'Entrenador')

    # Vincular juan_miembro con User
    try:
        user = User.objects.get(username='juan_miembro')
        miembro, created = Miembro.objects.get_or_create(
            dni='12345679',
            defaults={
                'nombre': 'Juan',
                'apellido': 'Pérez',
                'email': 'juan.miembro@test.com',
                'tipo_miembro': 'REGULAR',
                'activo': True,
                'usuario_id': user.id,
            }
        )
        if not created and miembro.usuario_id != user.id:
            miembro.usuario_id = user.id
            miembro.save()
    except User.DoesNotExist:
        pass

    # Crear Entrenador para usuario 'entrenador'
    try:
        user = User.objects.get(username='entrenador')
        entrenador, created = Entrenador.objects.get_or_create(
            email='entrenador@test.com',
            defaults={
                'nombre': 'Entrenador',
                'apellido': 'Principal',
                'especialidad': 'Entrenamiento General',
                'telefono': '555-0001',
                'activo': True,
                'usuario_id': user.id,
            }
        )
        if not created and entrenador.usuario_id != user.id:
            entrenador.usuario_id = user.id
            entrenador.save()
    except User.DoesNotExist:
        pass


def unlink_test_users(apps, schema_editor):
    """Deshacer vinculación"""
    Miembro = apps.get_model('miembros', 'Miembro')
    Miembro.objects.filter(usuario__username='juan_miembro').update(usuario=None)


class Migration(migrations.Migration):

    dependencies = [
        ('miembros', '0004_create_test_users'),
        ('entrenadores', '0002_entrenador_usuario'),
    ]

    operations = [
        migrations.RunPython(link_test_users, unlink_test_users),
    ]
