# Generated by Django 5.0.6 on 2026-06-20 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membresias', '0001_initial'),
        ('miembros', '0004_alter_carnet_codigo_barras_imagen_alter_miembro_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='miembro',
            name='membresia_activa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='miembro_activo', to='membresias.membresia'),
        ),
    ]
