# Generated by Django 5.0.6 on 2026-06-20 22:20

from django.db import migrations


def assign_active_memberships(apps, schema_editor):
    """Assign each member their most recent active membership"""
    Miembro = apps.get_model('miembros', 'Miembro')
    Membresia = apps.get_model('membresias', 'Membresia')

    for miembro in Miembro.objects.all():
        # Get most recent active membership for this member
        membresia_activa = Membresia.objects.filter(
            miembro=miembro,
            estado='ACTIVA'
        ).order_by('-fecha_inicio').first()

        if membresia_activa:
            miembro.membresia_activa = membresia_activa
            miembro.save(update_fields=['membresia_activa'])


def reverse_assignment(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('miembros', '0005_miembro_membresia_activa'),
    ]

    operations = [
        migrations.RunPython(assign_active_memberships, reverse_assignment),
    ]
