# Generated by Django 5.0.6 on 2026-06-20 22:28

from django.db import migrations, models
import django.db.models.deletion


def assign_default_membresia(apps, schema_editor):
    """Assign a default membership to members without one"""
    Miembro = apps.get_model('miembros', 'Miembro')
    Membresia = apps.get_model('membresias', 'Membresia')

    # Get any active membership to use as default
    default_membresia = Membresia.objects.filter(estado='ACTIVA').first()

    if default_membresia:
        # Assign to members without membership
        Miembro.objects.filter(membresia_activa__isnull=True).update(
            membresia_activa=default_membresia
        )


def reverse_requirement(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('miembros', '0006_assign_membresias_activas'),
        ('membresias', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(assign_default_membresia, reverse_requirement),
        migrations.AlterField(
            model_name='miembro',
            name='membresia_activa',
            field=models.ForeignKey(
                help_text='Membresía activa del miembro - requerida para registrar cobros',
                on_delete=django.db.models.deletion.PROTECT,
                related_name='miembro_activo',
                to='membresias.membresia'
            ),
        ),
    ]
