# Generated by Django 5.0.6 on 2026-06-20 23:14

from django.db import migrations
import django.db.models.deletion
from django.db import models


def copy_tipo_membresia(apps, schema_editor):
    """Copy tipo from membresia_activa to tipo_membresia_activa"""
    Miembro = apps.get_model('miembros', 'Miembro')
    for miembro in Miembro.objects.all():
        if miembro.membresia_activa_id:
            miembro.tipo_membresia_activa_id = miembro.membresia_activa.tipo_id
            miembro.save(update_fields=['tipo_membresia_activa_id'])


def reverse_copy(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('miembros', '0007_make_membresia_activa_required'),
        ('membresias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='miembro',
            name='tipo_membresia_activa',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='miembros_activos',
                to='membresias.tipomembresia'
            ),
        ),
        migrations.RunPython(copy_tipo_membresia, reverse_copy),
        migrations.RemoveField(
            model_name='miembro',
            name='membresia_activa',
        ),
        migrations.AlterField(
            model_name='miembro',
            name='tipo_membresia_activa',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='miembros_activos',
                to='membresias.tipomembresia'
            ),
        ),
    ]
