# Generated by Django 5.0.6 on 2026-06-13 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('membresias', '0001_initial'),
        ('miembros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cobro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descuento_porcentaje', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('monto_final', models.DecimalField(decimal_places=2, max_digits=10)),
                ('forma_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta'), ('TRANSFERENCIA', 'Transferencia')], max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True)),
                ('membresia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membresias.membresia')),
                ('miembro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cobros', to='miembros.miembro')),
            ],
            options={
                'verbose_name_plural': 'Cobros',
            },
        ),
        migrations.CreateModel(
            name='Comprobante',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('cobro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comprobante', to='cobros.cobro')),
            ],
            options={
                'verbose_name_plural': 'Comprobantes',
            },
        ),
    ]
