# Generated by Django 5.0.6 on 2026-06-13 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('miembros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('hora', models.TimeField(auto_now_add=True)),
                ('metodo', models.CharField(choices=[('BARCODE', 'Código de barras'), ('MANUAL', 'Manual')], default='BARCODE', max_length=10)),
                ('miembro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='miembros.miembro')),
            ],
            options={
                'verbose_name_plural': 'Asistencias',
            },
        ),
    ]
