# Generated by Django 5.0.6 on 2026-06-13 21:06

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('miembros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoMembresia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('duracion_dias', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name_plural': 'Tipos de membresía',
            },
        ),
        migrations.CreateModel(
            name='Membresia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('VENCIDA', 'Vencida'), ('CANCELADA', 'Cancelada')], default='ACTIVA', max_length=20)),
                ('miembro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membresias', to='miembros.miembro')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='membresias.tipomembresia')),
            ],
            options={
                'verbose_name_plural': 'Membresías',
            },
        ),
    ]
