# Generated by Django 5.0.6 on 2026-06-21 00:19

from django.db import migrations
from datetime import date, timedelta


def create_active_membresias(apps, schema_editor):
    """Create active Membresia instances for members with tipo_membresia_activa"""
    Miembro = apps.get_model('miembros', 'Miembro')
    Membresia = apps.get_model('membresias', 'Membresia')

    for miembro in Miembro.objects.filter(tipo_membresia_activa__isnull=False):
        # Check if active membresia already exists for this type
        existing = Membresia.objects.filter(
            miembro=miembro,
            tipo=miembro.tipo_membresia_activa,
            estado='ACTIVA'
        ).exists()

        if not existing:
            # Create new active membership starting today
            fecha_inicio = date.today()
            fecha_fin = fecha_inicio + timedelta(days=miembro.tipo_membresia_activa.duracion_dias)

            Membresia.objects.create(
                miembro=miembro,
                tipo=miembro.tipo_membresia_activa,
                fecha_inicio=fecha_inicio,
                fecha_fin=fecha_fin,
                estado='ACTIVA'
            )


def reverse_create(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('membresias', '0001_initial'),
        ('miembros', '0008_change_membresia_to_tipo'),
    ]

    operations = [
        migrations.RunPython(create_active_membresias, reverse_create),
    ]
