# Generated by Django 5.0.6 on 2026-06-15 18:36

from django.db import migrations
from datetime import date, timedelta


def create_test_membresias(apps, schema_editor):
    """Crear tipos de membresía y asignar al miembro de prueba"""
    TipoMembresia = apps.get_model('membresias', 'TipoMembresia')
    Membresia = apps.get_model('membresias', 'Membresia')
    Miembro = apps.get_model('miembros', 'Miembro')

    # Crear tipos de membresía
    tipos_data = [
        ('Plan Mensual', 'Acceso ilimitado por 30 días', 29.99, 30),
        ('Plan Trimestral', 'Acceso ilimitado por 90 días', 79.99, 90),
        ('Plan Anual', 'Acceso ilimitado por 365 días', 249.99, 365),
        ('Plan Estudiante', 'Descuento para estudiantes - 30 días', 14.99, 30),
    ]

    tipos_membresia = {}
    for nombre, desc, precio, duracion in tipos_data:
        tipo, created = TipoMembresia.objects.get_or_create(
            nombre=nombre,
            defaults={'descripcion': desc, 'precio': precio, 'duracion_dias': duracion}
        )
        tipos_membresia[nombre] = tipo

    # Asignar membresía al miembro juan_miembro
    try:
        miembro = Miembro.objects.get(dni='12345679')
        membresia, created = Membresia.objects.get_or_create(
            miembro=miembro,
            defaults={
                'tipo': tipos_membresia['Plan Mensual'],
                'fecha_inicio': date.today(),
                'fecha_fin': date.today() + timedelta(days=30),
                'estado': 'ACTIVA'
            }
        )
    except Miembro.DoesNotExist:
        pass


def delete_test_membresias(apps, schema_editor):
    """Eliminar datos de prueba"""
    TipoMembresia = apps.get_model('membresias', 'TipoMembresia')
    TipoMembresia.objects.filter(nombre__in=[
        'Plan Mensual', 'Plan Trimestral', 'Plan Anual', 'Plan Estudiante'
    ]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('membresias', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_test_membresias, delete_test_membresias),
    ]
