# Generated by Django 5.0.6 on 2026-06-14 03:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=50)),
                ('id_objeto', models.IntegerField()),
                ('accion', models.CharField(choices=[('CREATE', 'Creación'), ('UPDATE', 'Actualización'), ('DELETE', 'Eliminación')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('cambios', models.JSONField(blank=True, default=dict)),
                ('descripcion', models.TextField(blank=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Auditoría',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['modelo', 'id_objeto'], name='historial_a_modelo_e7da25_idx'), models.Index(fields=['-timestamp'], name='historial_a_timesta_4d4c98_idx'), models.Index(fields=['usuario'], name='historial_a_usuario_4985c4_idx')],
            },
        ),
    ]
